# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8Yo9HITQ_yUy1BP-jce4-tAOanPjY50
"""

for i in range(1, 31):
    if i % 2 == 0:
        print(i)

for i in range(2, 31, 2):
    print(i)